development:
  adapter: sqlite3
  database: tmp/area17pong_development.db

test: &test
  adapter: sqlite3
  database: tmp/area17pong_test.db

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: area17pong
  password:
  min_messages: warning
  database: area17pong_production
